apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: build-artifacts
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: efs-pv-{{ .Values.envName }}
  storageClassName: efs-sc
  volumeMode: Filesystem
