steps:
  - name: "gcr.io/kaniko-project/executor"
    args:
      - --destination=gcr.io/$PROJECT_ID/amplication:$SHORT_SHA
      - --cache=true
      - --cache-ttl=10h
  - name: "hashicorp/terraform:0.13.0"
    args: ["init"]
    dir: terraform
  - name: "hashicorp/terraform:0.13.0"
    args: ["apply", "-auto-approve"]
    dir: terraform
    env:
      - "TF_VAR_image_id=gcr.io/$PROJECT_ID/amplication:$SHORT_SHA"
