steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/amplication:$SHORT_SHA", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/amplication:$SHORT_SHA"]
  - name: "hashicorp/terraform:0.13.0"
    args: ["init"]
  - name: "hashicorp/terraform:0.13.0"
    args: ["apply", "-auto-approve"]
    dir: terraform
    env:
      - "TF_VAR_image_id=gcr.io/$PROJECT_ID/amplication:$SHORT_SHA"
images:
  - "gcr.io/$PROJECT_ID/amplication:$SHORT_SHA"
