version: "3"
services:
  postgres:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis
  server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - POSTGRESQL_URL=postgres://postgres:5432
    ports:
      - "3000:3000"
    environment:
      POSTGRESQL_URL: postgres://postgres:5432
      REDIS_URL: redis://redis:6379
volumes:
  postgres: ~
