version: "3"
services:
  postgres:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
  server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - POSTGRESQL_URL=postgres://${POSTGRESQL_USER}:${POSTGRESQL_PASSWORD}@postgres:5432
    ports:
      - "3000:3000"
    environment:
      POSTGRESQL_URL: postgres://${POSTGRESQL_USER}:${POSTGRESQL_PASSWORD}@postgres:5432
      JWT_SECRET: "${JWT_SECRET}"
      SERVICE_JWT_SECRET: "${SERVICE_JWT_SECRET}"
      BCRYPT_SALT_OR_ROUNDS: "${BCRYPT_SALT_OR_ROUNDS}"
volumes:
  postgres: ~
