steps:
  - id: "terraform-init"
    name: "hashicorp/terraform:0.13.0"
    args: ["init"]
    dir: terraform

  - id: "terraform-apply"
    name: "hashicorp/terraform:0.13.0"
    args:
      - "apply"
      - "-auto-approve"
      # 20 minutes
      - "-lock-timeout=1200s"
    dir: terraform
    env:
      - "TF_VAR_image_id=$_IMAGE_ID"

  - name: "node:12-stretch"
    entrypoint: bash
    args:
      - -c
      - |
        set -e;
        # Run Cloud SQL Proxy
        DB_PORT=5432;
        wget -O /workspace/cloud_sql_proxy https://storage.googleapis.com/cloudsql-proxy/v1.16/cloud_sql_proxy.linux.386;
        chmod +x /workspace/cloud_sql_proxy;
        /workspace/cloud_sql_proxy -dir=/workspace -instances=$PROJECT_ID:$_REGION:$_DB_INSTANCE_NAME=tcp:$DB_PORT & sleep 2
        # Run migrate
        docker run \
        --env POSTGRESQL_URL="postgresql://$_POSTGRESQL_USER:$_POSTGRESQL_PASSWORD@localhost:$DB_PORT/$_POSTGRESQL_DB" \
        $_IMAGE_ID \
        bash \
        -c \
        "cd packages/amplication-server/prisma/; npx @prisma/cli migrate up --auto-approve --experimental;"
# 1 hour
timeout: 3600s
