apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dsg-jobs-{{ .Values.envName }}-dsg
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: dsg-jobs-{{ .Values.envName }}-dsg
  storageClassName: efs-sc
  volumeMode: Filesystem
