steps:
- name: gcr.io/cloud-builders/docker
  args:
  - pull
  - gcr.io/cloudsql-docker/gce-proxy:1.11
- name: gcr.io/cloud-builders/docker
  args:
  - run
  - "-d"
  - "--network=cloudbuild"
  - "-v"
  - "/cloudsql:/cloudsql"
  - gcr.io/cloudsql-docker/gce-proxy:1.11
  - "/cloud_sql_proxy"
  - "-dir=/cloudsql"
  - "-instances=$PROJECT_ID:$_REGION:$_DB_INSTANCE"
- name: gcr.io/cloud-builders/docker
  args:
  - run
  - "--network=cloudbuild"
  - "-v"
  - "/cloudsql:/cloudsql"
  - "--env"
  - POSTGRESQL_URL=postgresql://$_POSTGRESQL_USER:$_POSTGRESQL_PASSWORD@127.0.0.1/$_POSTGRESQL_DB?host=?host=/cloudsql/$PROJECT_ID:$_REGION:$_DB_INSTANCE
  - "$_IMAGE_ID"
  - npm
  - run
  - db:init