amplication-server:
  secrets:
    GITHUB_APP_CLIENT_SECRET: GITHUB_APP_CLIENT_SECRET_PLACE_HOLDER
    GITHUB_APP_PRIVATE_KEY: GITHUB_APP_PRIVATE_KEY_PLACE_HOLDER
    GITHUB_CLIENT_SECRET: GITHUB_CLIENT_SECRET_PLACE_HOLDER
    POSTGRESQL_PASSWORD: POSTGRESQL_PASSWORD_PLACE_HOLDER
    POSTGRESQL_URL: POSTGRESQL_URL_PLACE_HOLDER