global:
  pvc:
    name: mor-efs-claim
  pv:
    name: efs-pv-mor

amplication-client:
  service:
    hostname: app-custom.amplication-dev.com
  config:
    env:
      REACT_APP_DATA_SOURCE: "https://server-custom.amplication-dev.com/graphql"
      REACT_APP_GITHUB_CONTROLLER_LOGIN_URL: "https://server-custom.amplication-dev.com/github"
      REACT_APP_GITHUB_CLIENT_ID: value

amplication-server:
  ingress:
    hostname: server-custom.amplication-dev.com
  config:
    env:

      HOST: "https://server-custom.amplication-dev.com"
      CLIENT_HOST: 'https://app-custom.amplication-dev.com'

      #GCP - APPS Builder

      DEFAULT_DISK: gcs
      LOCAL_DISK_ROOT: /artifacts
      CONTAINER_BUILDER_DEFAULT: cloud-build
      GCS_BUCKET: amplication-artifacts

      #GCP - APPS Deployer
      DEPLOYER_DEFAULT: gcp

      GCP_APPS_PROJECT_ID: amplication-apps
      GCP_APPS_REGION: us-east1
      GCP_APPS_TERRAFORM_STATE_BUCKET: amplication-apps-state-bucket
      GCP_APPS_DATABASE_INSTANCE: apps-database-instance
      GCP_APPS_DOMAIN: staging.amplication.app

      DOCKER_HOST: tcp://docker:2375

      #GitHub App
      GITHUB_APP_APP_ID: "195638"
      GITHUB_APP_CLIENT_ID: "Iv1.7c4ec6671b7c8cd7"
      GITHUB_APP_INSTALLATION_URL: "https://github.com/apps/amplicaiton-server-staging-os/installations/new?state={state}"

      #GitHub OAuth App
      GITHUB_CLIENT_ID: "aa4d2f3ccd7d47cbbf71"
      GITHUB_SECRET_SECRET_NAME: "projects/948093699220/secrets/github-secret-amplication-aws/versions/1"
      GITHUB_REDIRECT_URI: "https://server-custom.amplication-dev.com/github/callback"
      
amplication-git-push-webhook-service:
  ingress:
    hostname: webhook-mor.amplication-dev.com
  config:
    env:
      KAFKA_BROKERS: '["amplication-mor-cp-kafka-headless:9092"]'
      KAFKA_REPOSITORY_PUSH_QUEUE: git.external.push.event.0
      KAFKA_CLIENT_ID: git-push-webhook-service
      KAFKA_GROUP_ID: amplication-git-push-webhook-service

amplication-git-pull-service:
  config:
    env:
      NODE_ENV: "production"

      #EFS
      STORAGE_PATH: /amplication-data/git-data
      MAX_SNAPSHOTS: "100"

      #GitHub App
      GITHUB_APP_APP_ID: "215215"
      GITHUB_APP_CLIENT_ID: "Iv1.a8ac08d4d3788314"
      GIT_DEFAULT_ORIGIN_NAME: origin

      KAFKA_BROKERS: '["amplication-mor-cp-kafka-headless:9092"]'
      KAFKA_CLIENT_ID: git-pull-service
      KAFKA_GROUP_ID: git-pull-service-group

      KAFKA_REPOSITORY_PUSH_QUEUE: git.external.push.event.0

amplication-git-pull-request-service:
  config:
    env:
      KAFKA_BROKERS: '["amplication-mor-cp-kafka-headless:9092"]'
      KAFKA_CLIENT_ID: git-pull-request-service
      KAFKA_GROUP_ID: git-pull-request-service-group
      GENERATE_PULL_REQUEST_TOPIC: git.internal.pull-request.request.0
      BASE_BUILDS_FOLDER: /amplication-data/build-data
      GITHUB_APP_APP_ID: "215215"

amplication-storage-gateway:
  ingress:
    hostname: server-mor.amplication-dev.com
  config:
    env:
      KAFKA_BROKERS: '["amplication-mor-cp-kafka-headless:9092"]'
      BASE_BUILDS_FOLDER: /amplication-data/build-data
      GITHUB_APP_APP_ID: "215215"