cp-helm-charts:
  enabled: false

postgres:
  install: false

amplication-client:
  service:
    hostname: app.staging-os.amplication-dev.com
    certificatearn: arn:aws:acm:us-east-1:407256539111:certificate/bc3442ea-ddcb-4870-b4ba-79144e623d71
  config:
    env:
      REACT_APP_DATA_SOURCE: "https://server.staging-os.amplication-dev.com/graphql"
      REACT_APP_GITHUB_CONTROLLER_LOGIN_URL: "https://server.staging-os.amplication-dev.com/github"

amplication-server:
  postgres:
    install: false
  ingress:
    enabled: true
    hostname: server.staging-os.amplication-dev.com
  config:
    env:
      HOST: "https://server.staging-os.amplication-dev.com"
      CLIENT_HOST: "https://app.staging-os.amplication-dev.com"

      KAFKA_BROKERS: "b-2.amplication-useast1-s.bqx2i9.c22.kafka.us-east-1.amazonaws.com:9094,b-1.amplication-useast1-s.bqx2i9.c22.kafka.us-east-1.amazonaws.com:9094"
      
      #GitHub App
      GITHUB_APP_APP_ID: "195638"
      GITHUB_APP_CLIENT_ID: "Iv1.7c4ec6671b7c8cd7"
      GITHUB_APP_INSTALLATION_URL: "https://github.com/apps/amplicaiton-server-staging-os/installations/new?state={state}"

      #GitHub OAuth App
      GITHUB_CLIENT_ID: "aa4d2f3ccd7d47cbbf71"
      GITHUB_SECRET_SECRET_NAME: "projects/948093699220/secrets/github-secret-amplication-aws/versions/1"
      GITHUB_REDIRECT_URI: "https://server.staging-os.amplication-dev.com/github/callback"

amplication-git-push-webhook-service:
  postgres:
    install: false
  ingress:
    enabled: true
    hostname: https://webhook.staging-os.amplication-dev.com
  config:
    env:
      KAFKA_BROKERS: "b-2.amplication-useast1-s.bqx2i9.c22.kafka.us-east-1.amazonaws.com:9094,b-1.amplication-useast1-s.bqx2i9.c22.kafka.us-east-1.amazonaws.com:9094"

amplication-git-pull-service:
  postgres:
    install: false
  config:
    env:
      KAFKA_BROKERS: "b-2.amplication-useast1-s.bqx2i9.c22.kafka.us-east-1.amazonaws.com:9094,b-1.amplication-useast1-s.bqx2i9.c22.kafka.us-east-1.amazonaws.com:9094"
      
      #GitHub App
      GITHUB_APP_APP_ID: "195638"
      GITHUB_APP_CLIENT_ID: "Iv1.7c4ec6671b7c8cd7"
      GIT_DEFAULT_ORIGIN_NAME: origin
      GITHUB_APP_PRIVATE_KEY:

amplication-git-pull-request-service:
  config:
    env:
      KAFKA_BROKERS: "b-2.amplication-useast1-s.bqx2i9.c22.kafka.us-east-1.amazonaws.com:9094,b-1.amplication-useast1-s.bqx2i9.c22.kafka.us-east-1.amazonaws.com:9094"



