amplication-client:
  deployment:
    image:
      repository: 407256539111.dkr.ecr.us-east-1.amazonaws.com/amplication-client-dev
  service:
    hostname: app.staging-os.amplication-dev.com
    certificatearn: arn:aws:acm:us-east-1:407256539111:certificate/a9adf002-719c-45e0-9dd5-4965bd5ec585

amplication-server:
  deployment:
    image:
      repository: 407256539111.dkr.ecr.us-east-1.amazonaws.com/amplication-server-dev
  postgres:
    install: false
  ingress:
    enabled: true
    hostname: server.staging-os.amplication-dev.com
  config:
    env:
      GITHUB_APP_APP_ID: "189214"
      CONTAINER_BUILDER_DEFAULT: docker
      GITHUB_APP_CLIENT_ID: "Iv1.7eb319d8e3c170d7"
      GITHUB_APP_INSTALLATION_URL: "https://github.com/apps/amplication-aws/installations/new?state={state}"
      GITHUB_REDIRECT_URI: "https://server.staging-os.amplication-dev.com/github/callback"
      GITHUB_SECRET_SECRET_NAME: "projects/948093699220/secrets/github-secret-amplication-aws/versions/1"
      HOST: "https://server.staging-os.amplication-dev.com"
      GITHUB_CLIENT_ID: "a4e9055e5f21448d6de7"
      KAFKA_BROKERS: []
      KAFKA_CLIENT_ID: 
      KAFKA_GROUP_ID:


amplication-git-push-webhook-service:
  postgres:
    install: false
  ingress:
    enabled: true
    hostname: https://webhook.staging-os.amplication-dev.com
  config:
    env:
      KAFKA_BROKERS: [localhost:9092]
      KAFKA_CLIENT_ID:
      KAFKA_GROUP_ID: git-pull-event


amplication-git-pull-service:
  postgres:
    install: false
  config:
    env:
      POSTGRESQL_USER: admin
      POSTGRESQL_PASSWORD: admin
      POSTGRESQL_PORT: "5432"
      POSTGRESQL_URL: postgres://admin:admin@localhost:5432
      COMPOSE_PROJECT_NAME: amplication-git-pull-service
      NODE_ENV: "production"
      STORAGE_PATH: /pull-data
      MAX_SNAPSHOTS:
      GIT_DEFAULT_ORIGIN_NAME: origin
      GITHUB_APP_APP_ID:
      GITHUB_APP_PRIVATE_KEY:
      KAFKA_BROKERS: [localhost:9092]
      KAFKA_GROUP_ID: git-pull-event

amplication-git-pull-request-service:
  config:
    env:
      KAFKA_BROKERS:
      KAFKA_GROUP_ID: 




