amplication-client:
  image:
    repository: 407256539111.dkr.ecr.us-east-1.amazonaws.com/amplication-client
  service:
    hostname: app.staging-os.amplication-dev.com
    certificatearn: arn:aws:acm:us-east-1:407256539111:certificate/bc3442ea-ddcb-4870-b4ba-79144e623d71
  config:
    env:
      REACT_APP_DATA_SOURCE: "https://server.staging-os.amplication-dev.com/graphql"
      REACT_APP_GITHUB_CONTROLLER_LOGIN_URL: "https://server.staging-os.amplication-dev.com/github"
      REACT_APP_GITHUB_CLIENT_ID: value

amplication-server:
  image:
    repository: 407256539111.dkr.ecr.us-east-1.amazonaws.com/amplication-server
  postgres:
    install: false
  ingress:
    enabled: true
    hostname: server.staging-os.amplication-dev.com
  config:
    env:
      HOST: "https://server.staging-os.amplication-dev.com"
      CLIENT_HOST: "https://app.staging-os.amplication-dev.com"

      GENERATE_PULL_REQUEST_TOPIC: git.internal.pull-request.request.0
      KAFKA_BROKERS: '["b-2.amplication-useast1-s.bqx2i9.c22.kafka.us-east-1.amazonaws.com:9094","b-1.amplication-useast1-s.bqx2i9.c22.kafka.us-east-1.amazonaws.com:9094"]'
      KAFKA_CLIENT_ID: amplication-server
      KAFKA_GROUP_ID: amplication-server-group

      #EFS
      BASE_BUILDS_FOLDER: /amplication-data/build-data

      #GCP - APPS Builder
      DEFAULT_DISK: gcs
      LOCAL_DISK_ROOT: /artifacts
      CONTAINER_BUILDER_DEFAULT: cloud-build
      GCS_BUCKET: amplication-artifacts

      #GCP - APPS Deployer
      DEPLOYER_DEFAULT: gcp

      GCP_APPS_PROJECT_ID: amplication-apps
      GCP_APPS_REGION: us-east1
      GCP_APPS_TERRAFORM_STATE_BUCKET: amplication-apps-state-bucket
      GCP_APPS_DATABASE_INSTANCE: apps-database-instance
      GCP_APPS_DOMAIN: staging.amplication.app

      DOCKER_HOST: tcp://docker:2375

      #GitHub App
      GITHUB_APP_APP_ID: "195638"
      GITHUB_APP_CLIENT_ID: "Iv1.7c4ec6671b7c8cd7"
      GITHUB_APP_INSTALLATION_URL: "https://github.com/apps/amplicaiton-server-staging-os/installations/new?state={state}"

      #GitHub OAuth App
      GITHUB_CLIENT_ID: "aa4d2f3ccd7d47cbbf71"
      GITHUB_SECRET_SECRET_NAME: "projects/948093699220/secrets/github-secret-amplication-aws/versions/1"
      GITHUB_REDIRECT_URI: "https://server.staging-os.amplication-dev.com/github/callback"

amplication-git-push-webhook-service:
  postgres:
    install: false
  ingress:
    enabled: true
    hostname: https://webhook.staging-os.amplication-dev.com
  config:
    env:
      KAFKA_BROKERS: '["b-2.amplication-useast1-s.bqx2i9.c22.kafka.us-east-1.amazonaws.com:9094","b-1.amplication-useast1-s.bqx2i9.c22.kafka.us-east-1.amazonaws.com:9094"]'
      KAFKA_REPOSITORY_PUSH_QUEUE: git.external.push.event.0
      KAFKA_CLIENT_ID: git-push-webhook-service
      KAFKA_GROUP_ID: amplication-git-push-webhook-service

amplication-git-pull-service:
  postgres:
    install: false
  config:
    env:
      #ILIA
      #NEW SECRETS
      #POSTGRESQL_USER: admin
      #POSTGRESQL_PASSWORD: admin
      #POSTGRESQL_PORT: "5432"
      #POSTGRESQL_URL: postgres://admin:admin@localhost:5432

      #EXISTS SECRETS
      #GITHUB_APP_PRIVATE_KEY:
      #GITHUB_APP_CLIENT_SECRET:

      NODE_ENV: "production"

      #EFS
      STORAGE_PATH: /amplication-data/build-data
      MAX_SNAPSHOTS: 100

      #GitHub App
      GITHUB_APP_APP_ID: "195638"
      GITHUB_APP_CLIENT_ID: "Iv1.7c4ec6671b7c8cd7"
      GIT_DEFAULT_ORIGIN_NAME: origin
      KAFKA_TOPIC: git.external.push.event.0
      GITHUB_APP_PRIVATE_KEY:
      KAFKA_BROKERS: '["b-2.amplication-useast1-s.bqx2i9.c22.kafka.us-east-1.amazonaws.com:9094","b-1.amplication-useast1-s.bqx2i9.c22.kafka.us-east-1.amazonaws.com:9094"]'
      KAFKA_CLIENT_ID: git-pull-service
      KAFKA_GROUP_ID: git-pull-service-group

amplication-git-pull-request-service:
  config:
    env:
      KAFKA_BROKERS: '["b-2.amplication-useast1-s.bqx2i9.c22.kafka.us-east-1.amazonaws.com:9094","b-1.amplication-useast1-s.bqx2i9.c22.kafka.us-east-1.amazonaws.com:9094"]'
      KAFKA_CLIENT_ID: git-pull-request-service
      KAFKA_GROUP_ID: git-pull-request-service-group
      GENERATE_PULL_REQUEST_TOPIC: git.internal.pull-request.request.0
      BASE_BUILDS_FOLDER: /amplication-data/build-data
