name: Continuous Integration (Nx)

on:
  workflow_dispatch:
  push:
    branches:
      - feature/nx
  pull_request:

jobs:
  # main:
  #   name: Nx Cloud - Main Job
  #   uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.7
  #   with:
  #     number-of-agents: 3
  #     init-commands: |
  #       npx nx-cloud start-ci-run --stop-agents-after="build" --agent-count=3
  #     parallel-commands: |
  #       npx nx-cloud record -- npx nx workspace-lint
  #       npx nx-cloud record -- npx nx format:check
  #     parallel-commands-on-agents: |
  #       npx nx affected --target=lint --parallel=3
  #       npx nx affected --target=test --parallel=3 --ci --code-coverage
  #       npx nx affected --target=build --parallel=3

  test:
    name: Build
    runs-on: ubuntu-latest
    env:
      NX_BRANCH: ${{ github.head_ref }}
      NX_CLOUD_DISTRIBUTED_EXECUTION: "false"
      NX_CLOUD_ACCESS_TOKEN: ${{ github.secrets.NX_CLOUD_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: next

      - name: Install Dependencies
        run: npm ci

      - name: Nx Workspace Lint
        run: npx nx workspace-lint

      - name: Nx Format Check
        run: npx nx format:check

      - name: Lint
        run: npx nx affected --target=lint --parallel=3

      - name: Test
        run: npx nx affected --target=test --parallel=3
