name: delete-namespace
on:
  workflow_dispatch:
    inputs:
      namespace:
        type: choice
        description: Select the namespace you wish to delete
        default: shimi
        required: true
        options: 
        - shimi
        - mor
        - amit

jobs:
  delete-namespace:
    runs-on: ubuntu-18.04
    steps:
      - name: install argocd
        id: install-argocd
        run: |
          curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x /usr/local/bin/argocd
      - name: argocd login
        env: 
          ARGO_CD_PASSWORD: ${{ secrets.AWS_STAGING_OS_ARGOCD }}
        run: |
          ARGO_CD_URL="argocd.staging-os.amplication-dev.com"
          argocd login $ARGO_CD_URL --username admin --password $ARGO_CD_PASSWORD --grpc-web
      - name: delete namespace
        env:
          NAMESPACE: ${{ github.event.inputs.namespace }}
        run: |
          APPNAME="amplication-$NAMESPACE"
          set +e
          argocd app delete $APPNAME
  delete-pv:
    runs-on: ubuntu-18.04
    steps:
      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: connect to cluster
        env:
          AWS_REGION: us-east-1
          CLUSTER_NAME: useast1-staging-os
        run: aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME
      - name: delete pv
        env:
          NAMESPACE: ${{ github.event.inputs.namespace }}
        run: |
          kubectl delete pv efs-pv-$NAMESPACE


