name: delete-ns
on:
  workflow_dispatch:
    inputs:
      namespace:
        type: string
        description: Which namespace you want to delete
        default: shimi
        required: true

jobs:
  check-ns-name:
    runs-on: ubuntu-18.04
    outputs:
      namespace_valid: ${{ steps.check-ns.outputs.namespace_valid }}
    steps:
      - name: check namespace
        id: check-ns
        env: 
          NAMESPACE: ${{ github.event.inputs.namespace }}
        run: |
          NAMESPACE=$NAMESPACE
          echo "namespce: $NAMESPACE"
          if [[ "$NAMESPACE" == "staging" || "$NAMESPACE" == "staging-os" || "$NAMESPACE" == "prod" ]]; then
            echo "This is not a dynamic namespace."
            echo "::set-output name=namespace_valid::false"
          else
            echo "::set-output name=namespace_valid::true"
          fi
  delete-ns:
    runs-on: ubuntu-18.04
    needs: [check-ns-name]
    if: ${{ needs.check-ns-name.outputs.namespace_valid == "true" }}
    steps:
      - uses: actions/checkout@v2
      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: set cluster name
        id: set-cluster-name
        run: |
          CLUSTER_NAME="useast1-staging-os"
          echo "Will run to $CLUSTER_NAME eks cluster"
          echo "CLUSTER_NAME=$CLUSTER_NAME" >> $GITHUB_ENV
        env:
          CLUSTER-ENV: ${{ github.event.inputs.cluster-env }}
      - name: connect to cluster
        id: connect-cluster
        run: |
          aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME
        env:
          AWS_REGION: us-east-1
      - name: install argocd
        id: install-argocd
        run: |
          curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x /usr/local/bin/argocd
      - name: check if namespace exist
        id: ns-exist
        env: 
          NAMESPACE: ${{ github.event.inputs.namespace }}
        run: |
          set +e
          Get_app="$(argocd app list)"
          if [[ -z "$Get_app" ]]
          then
            echo "namespace doesn't exist"
            echo "::set-output name=app_exist::false"
          else
            echo "namespace exists"
            echo "::set-output name=app_exist::true"
          fi
      - name: delete ns
        if: ${{ steps.ns-exist.outputs.app_exist == "true" }}
        env:
          NAMESPACE: ${{ github.event.inputs.namespace }}
          ARGO_CD_PASSWORD: ${{ secrets.AWS_STAGING_OS_ARGOCD }}
        run: |
          ARGO_CD_URL="argocd.staging-os.amplication-dev.com"
          APPNAME="amplication-$NAMESPACE"
          argocd login $ARGO_CD_URL --username admin --password $ARGO_CD_PASSWORD --grpc-web
          argocd app delete $APPNAME








