name: FORK-TO-BRANCH

on:
  workflow_dispatch:
    inputs:
      source-branch:
        type: string
        description: Which branch to use for deployment
        default: main
        required: true
      contributor_name:
        type: string
        description: write your github-user name
        required: true
  pull_request:
    branches: ['master','release/*']
    types: [opened, reopened]

jobs:
  Check_branch:
    runs-on: ubuntu-latest
  steps:
    - name:
      run: 







