name: FORK-TO-BRANCH

on:
  workflow_dispatch:
    inputs:
      source-branch:
        type: string
        description: The name of the branch from forked-repo.
        required: true
      contributor-name:
        type: string
        description: write the contributor github username
        required: true

jobs:
  create_branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }} # need to add PAT

      - name: Check if branch exists
        run: |
          existed_in_repo=$(git ls-remote --heads origin feature/${{ github.event.inputs.source-branch }})
          if [[ -z ${existed_in_repo} ]]
          then
            echo "branch feature/${{ github.event.inputs.source-branch }} is not exists"
          else
            git push origin --delete feature/${{ github.event.inputs.source-branch }}
            echo "branch feature/${{ github.event.inputs.source-branch }} deleted" 
          fi
  
      - name: Git remote add forked repo
        run: |
          git remote add upstream https://github.com/${{ github.event.inputs.contributor-name }}/amplication.git
          git fetch --all
          git checkout upstream/${{ github.event.inputs.source-branch }}
          git checkout -b feature/${{ github.event.inputs.source-branch }}
          git push --set-upstream origin feature/${{ github.event.inputs.source-branch }}
          
          echo "Forked branch ${{ github.event.inputs.contributor-name }}:${{ github.event.inputs.source-branch }} has been pushed to amplication repo in feature/${{ github.event.inputs.source-branch }}"











