name: Staging - Terraform Plam

on:
  workflow_dispatch:
    inputs:
      image-id:
        description: "Amplication Image"
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: hashicorp/setup-terraform@v1
      - run: terraform init
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        working-directory: terraform/envs/dev
      - run: terraform plan
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          TF_VAR_image_id: ${{ github.event.inputs.image-id }}
          TF_VAR_GITHUB_APP_PRIVATE_KEY: ${{ secrets.STAGING_GITHUB_APP_PRIVATE_KEY }}
          TF_VAR_GITHUB_APP_CLIENT_SECRET: ${{ secrets.STAGING_GITHUB_APP_CLIENT_SECRET }}
        working-directory: terraform/envs/dev
